language: generic
sudo: required
dist: trusty
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
  - env: EMACS_VERSION=25.1
  - env: EMACS_VERSION=25.2
  - env: EMACS_VERSION=25.3
env:
  global:
  - EMACS_DIR=$HOME/emacs
  - EMACSBIN=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
- sudo apt install gnutls-bin
- curl -OL https://raw.githubusercontent.com/vermiculus/emake.el/master/build-emacs
# You generally don't want 'x' in your own projects, but for the
# purposes of actually developing `build-emacs', it's useful
# information to have.  See the example for how you *should* be
# doing all this!
- bash -ex build-emacs
install:
- $EMACSBIN --version
# Work around the Emacs GPG key issue
# https://www.reddit.com/r/emacs/comments/ddjo76/emacs_gpg_key_issues/f2lztn1/
# Thanks to /u/npostavs and /u/AFewSentientNeurons
- curl -OL https://elpa.gnu.org/packages/gnu-elpa-keyring-update-2019.3.tar
- $EMACSBIN --batch -Q --funcall package-refresh-contents --eval '(package-install-file "gnu-elpa-keyring-update-2019.3.tar")'
- make makel.mk
- make makel-version
- make install-elpa-dependencies
script:
- make check
